export { default as Nav } from "../components/Nav/nav.js"
export { default as Header } from "../components/Header/header.js"
export { default as About } from "../components/About/about.js"
export { default as Projects } from "../components/Projects/projects.js"
export { default as Contact } from "../components/Contact/contact.js"
export { default as Footer } from "../components/Footer/footer.js"